openapi: "3.0.3"
info:
  title: Space Server API
  description: Space Server API
  version: "1.0.0"
servers:
- url: "/api/v1"
paths:
  /login:
    post:
      summary: Create a session cookie
      tags:
        - Auth
      requestBody:
        required: true
        content:
          x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        "401":
          description: Unauthorized. Wrong credentials
        "200":
          description: OK
  /logout:
    get:
      summary: Log out of current session
      tags:
        - Auth
      responses:
        "200":
          description: OK

  /upload:
    post:
      summary: Upload a file to be imported
      tags:
        - Imports
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "200":
          description: OK
        "401":
          $ref: "#/components/responses/Unauthorized"

  /imports:
    get:
      summary: Get all imports
      tags:
        - Imports
      responses:
        "200":
          description: Returns a list of all imports
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Import"
        "401":
          $ref: "#/components/responses/Unauthorized"

  /imports/{guid}:
    parameters:
      - in: path
        name: guid
        required: true
        schema:
          type: string
        description: GUID of import
    get:
      summary: Get a specific import
      tags:
        - Imports
      responses:
        "200":
          description: Returns the specified import
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Import"
        "404":
          description: Import not found
        "401":
          $ref: "#/components/responses/Unauthorized"
    put:
      summary: Update a specific import
      tags:
        - Imports
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Import"
      responses:
        "200":
          description: Import updated successfully
        "404":
          description: Import not found
        "401":
          $ref: "#/components/responses/Unauthorized"
    delete:
      summary: Delete a specific import
      tags:
        - Imports
      responses:
        "200":
          description: Import deleted successfully
        "404":
          description: Import not found
        "401":
          $ref: "#/components/responses/Unauthorized"
  /imports/{guid}/edit/deskew:
    parameters:
      - in: path
        name: guid
        required: true
        schema:
          type: string
        description: GUID of the Import
      - in: query
        name: deskew
        required: false
        schema:
          type: integer
        description: deskew value
    post:
      summary: Run deskew on images
      tags:
        - Imports
      responses:
        "200":
          description: Operation successfull
        "404":
          description: Import not found
        "401":
          $ref: "#/components/responses/Unauthorized"
  /imports/{guid}/edit/color:
    parameters:
      - in: path
        name: guid
        required: true
        schema:
          type: string
        description: GUID of the Import
      - in: query
        name: fuzz
        required: false
        schema:
          type: integer
        description: fuzz value for removing background color
    post:
      summary: Run color adjustments on images
      tags:
        - Imports
      responses:
        "200":
          description: Operation successfull
        "404":
          description: Import not found
        "401":
          $ref: "#/components/responses/Unauthorized"
  /imports/{guid}/edit/crop:
    parameters:
      - in: path
        name: guid
        required: true
        schema:
          type: string
        description: GUID of the Import
      - in: query
        name: fuzz
        required: false
        schema:
          type: integer
        description: fuzz value for cropping background
    post:
      summary: Run background removal on images
      tags:
        - Imports
      responses:
        "200":
          description: Operation successfull
        "404":
          description: Import not found
        "401":
          $ref: "#/components/responses/Unauthorized"
  /imports/{guid}/edit/complete:
    parameters:
      - in: path
        name: guid
        required: true
        schema:
          type: string
        description: GUID of the Import
      - in: query
        name: deskew
        required: false
        schema:
          type: integer
        description: deskew value
      - in: query
        name: colorFuzz
        required: false
        schema:
          type: integer
        description: fuzz value for removing background color
      - in: query
        name: cropFuzz
        required: false
        schema:
          type: integer
        description: fuzz value for cropping background
    post:
      summary: Run image editing and create new thumbnails
      tags:
        - Imports
      responses:
        "200":
          description: Operation successfull
        "404":
          description: Import not found
        "401":
          $ref: "#/components/responses/Unauthorized"
  /imports/{guid}/pdf:
    parameters:
      - in: path
        name: guid
        required: true
        schema:
          type: string
        description: GUID of the Import
    get:
      summary: Get the PDF of the Import
      tags:
        - Imports
      responses:
        "200":
          description: Returns the original PDF
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        "404":
          description: Import not found
        "401":
          $ref: "#/components/responses/Unauthorized"
  /imports/{guid}/img/{page}:
    parameters:
      - in: path
        name: guid
        required: true
        schema:
          type: string
        description: GUID of the Import
      - in: path
        name: page
        required: true
        schema:
          type: integer
        description: the page number
    get:
      summary: Get the Image for the specified page
      tags:
        - Imports
      responses:
        "200":
          description: Returns the Image
          content:
            image/png:
              schema:
                type: string
                format: binary
        "404":
          description: Import not found
        "401":
          $ref: "#/components/responses/Unauthorized"
  /imports/{guid}/img/{page}/deskewed:
    parameters:
      - in: path
        name: guid
        required: true
        schema:
          type: string
        description: GUID of the Import
      - in: path
        name: page
        required: true
        schema:
          type: integer
        description: the page number
    get:
      summary: Get the deskewed Image for the specified page
      tags:
        - Imports
      responses:
        "200":
          description: Returns the Image
          content:
            image/png:
              schema:
                type: string
                format: binary
        "404":
          description: Import not found
        "401":
          $ref: "#/components/responses/Unauthorized"
  /imports/{guid}/img/{page}/color:
    parameters:
      - in: path
        name: guid
        required: true
        schema:
          type: string
        description: GUID of the Import
      - in: path
        name: page
        required: true
        schema:
          type: integer
        description: the page number
    get:
      summary: Get the color adjusted Image for the specified page
      tags:
        - Imports
      responses:
        "200":
          description: Returns the Image
          content:
            image/png:
              schema:
                type: string
                format: binary
        "404":
          description: Import not found
        "401":
          $ref: "#/components/responses/Unauthorized"
  /imports/{guid}/img/{page}/original:
    parameters:
      - in: path
        name: guid
        required: true
        schema:
          type: string
        description: GUID of the Import
      - in: path
        name: page
        required: true
        schema:
          type: integer
        description: the page number
    get:
      summary: Get the original Image for the specified page
      tags:
        - Imports
      responses:
        "200":
          description: Returns the Image
          content:
            image/png:
              schema:
                type: string
                format: binary
        "404":
          description: Import not found
        "401":
          $ref: "#/components/responses/Unauthorized"
  /imports/{guid}/thumb/{page}/{size}:
    parameters:
      - in: path
        name: guid
        required: true
        schema:
          type: string
        description: GUID of the Import
      - in: path
        name: page
        required: true
        schema:
          type: integer
        description: the page number
      - in: path
        name: size
        required: true
        schema:
          type: integer
        description: the size of the thumbnail (128, 256, 512)
    get:
      summary: Get the thumbnail for the specified page
      tags:
        - Imports
      responses:
        "200":
          description: Returns the Thumbnail
          content:
            image/png:
              schema:
                type: string
                format: binary
        "404":
          description: Import not found
        "401":
          $ref: "#/components/responses/Unauthorized"

  /documents:
    get:
      summary: Get all documents
      tags:
        - Documents
      responses:
        "200":
          description: Returns a list of all documents
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Document"
        "401":
          $ref: "#/components/responses/Unauthorized"

  /documents/{guid}:
    parameters:
      - in: path
        name: guid
        required: true
        schema:
          type: string
        description: GUID of document
    get:
      summary: Get a specific document
      tags:
        - Documents
      responses:
        "200":
          description: Returns the specified document
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Document"
        "404":
          description: Document not found
        "401":
          $ref: "#/components/responses/Unauthorized"
    put:
      summary: Update a specific document
      tags:
        - Documents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Document"
      responses:
        "200":
          description: Document updated successfully
        "404":
          description: Document not found
        "401":
          $ref: "#/components/responses/Unauthorized"
    delete:
      summary: Delete a specific document
      tags:
        - Documents
      responses:
        "200":
          description: Document deleted successfully
        "404":
          description: Document not found
        "401":
          $ref: "#/components/responses/Unauthorized"

  /users:
    get:
      summary: Get all users
      tags:
        - Users
      responses:
        "200":
          description: Returns a list of all users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "401":
          $ref: "#/components/responses/Unauthorized"
    put:
      summary: Update an existing user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: OK
        "400":
          description: User does not exist
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          description: Not allowed to update other users - can only be done by admin

  /users/{username}:
    parameters:
      - in: path
        name: username
        required: true
        schema:
          type: string
        description: Username of user
    get:
      summary: Get a specific user
      tags:
        - Users
      responses:
        "200":
          description: Returns the specified user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: User not found
        "401":
          $ref: "#/components/responses/Unauthorized"
    delete:
      summary: Delete a specific user
      tags:
        - Users
      responses:
        "200":
          description: User deleted successfully
        "404":
          description: User not found
        "401":
          $ref: "#/components/responses/Unauthorized"
  /users/password:
    post:
      summary: Change password for current Session-User
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PasswordChangeRequest"
      responses:
        "200":
          description: OK
        "400":
          description: Empty password
        "401":
          $ref: "#/components/responses/Unauthorized"

components:
  schemas:
    PasswordChangeRequest:
      type: object
      properties:
        old:
          type: string
        new:
          type: string
      required:
        - old
        - new
    NameChangeRequest:
      type: object
      properties:
        name:
          type: string
      required:
        - name
    User:
      type: object
      properties:
        username:
          type: string
        name:
          type: string
        admin:
          type: boolean
          description: Read-only property - Changes get ignored
        createdAt:
          $ref: "#/components/schemas/LocalDateTime"
        updatedAt:
          $ref: "#/components/schemas/LocalDateTime"
      required:
        - username
        - createdAt

    Document:
      type: object
      properties:
        id:
          type: integer
        guid:
          type: string
        createdAt:
          $ref: "#/components/schemas/LocalDateTime"
        updatedAt:
          $ref: "#/components/schemas/LocalDateTime"
      required:
        - id
        - guid
        - createdAt

    Import:
      type: object
      properties:
        id:
          type: integer
        guid:
          type: string
        type:
          type: string
        ocrLanguage:
          type: string
        pages:
          type: integer
        text:
          type: string
        date:
          $ref: "#/components/schemas/LocalDate"
        createdAt:
          $ref: "#/components/schemas/LocalDateTime"
        updatedAt:
          $ref: "#/components/schemas/LocalDateTime"
      required:
        - id
        - guid
        - type
        - pages
        - createdAt

    LocalDateTime:
      type: array
      items:
        type: integer

    LocalDate:
      type: array
      items:
        type: integer

  responses:
    Unauthorized:
      description: Unauthorized