ktor:
  application:
    modules:
      - de.axl.ApplicationKt.module
  deployment:
    host: 127.0.0.1
    port: 8080
jwt:
  issuer: "$SPACE_HOST"
  audience: "space-audience"
  realm: "space"
  secret: "$SPACE_SECRET"
space:
  swagger:
    enabled: true
  paths:
    base: "data"
    upload: "upload"
    docs: "docs"