ktor:
  application:
    modules:
      - de.axl.ApplicationKt.module
  deployment:
    host: 127.0.0.1
    port: 8080
session:
  cookie:
    age: 60 # max-age of session-cookie in seconds
    secure: true
    encrypt:
      key: ""
    signing:
      key: ""
space:
  swagger:
    enabled: false
  paths:
    data: "data"